GET http://localhost:3000/access-token
Authorization : Bearer 

###
//generate the access token
POST http://localhost:3000/initiate-stk-push
Content-Type: application/json

{
  "phone": "769784198",
  "amount": 2
}
