
version: '3'
services:
  mongo:
    image: mongo:4.2.2
    environment:
      
  
 # playground-web-frontend:
 #  image: playground-web-frontend:latest
 #  environment:
 #  PORT: 3000
 #  PROXY_API: http://playground-web-backend:8080/
 #  ports:
 #   - 3000:3000
  backendaraja:
    container_name: darajaimage
    depends_on:
      - mongo
    image: backendaraja:latest
    restart: always
    env_file:
      - .env
    environment:
      DATABASE_URI: $DATABASE_URI
    ports:
      - 5050:5050
    networks:
      -daraj-networks  